spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 5201314cb
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8080
  servlet:
    context-path: /crm  # 上下文路径

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名映射
